import type { OpenAPIV3 } from "openapi-types";

export const TAG_NAMES = {
  SYSTEM: "System",
  AUTH: "Authentication",
  USERS: "Users",
  ROLES: "Roles & Permissions",
  TEAMS: "Teams",
  SALE_TYPES: "Sale Types",
  SALE_TYPE_CATEGORIES: "Sale Type Categories",
  LEAD_TYPES: "Lead Types",
  LEADS: "Leads",
  LEAD_REGISTRATION: "Lead Registration",
  FRONT_DESK: "Front Desk",
  CLIENTS: "Clients",
  CLIENT_PAYMENTS: "Client Payments",
  CLIENT_PRODUCT_PAYMENTS: "Client Product Payments",
  MODULE_PAYMENTS: "Module Payments",
  MODULE_COUNTRIES: "Module Countries",
  MODULE_JOURNEY: "Module Journey",
  MODULE_REPORTS: "Module Reports",
  MODULE_VISA_CASES: "Module Visa Cases",
  MODULE_STAGES: "Module Stages",
  DASHBOARD: "Dashboard",
  ACTIVITY_LOGS: "Activity Logs",
  LEADERBOARD: "Leaderboard",
  MANAGER_TARGETS: "Manager Targets",
  TELECALLER_TARGETS: "Telecaller Targets",
  REPORTS: "Reports",
  MESSAGES: "Messages",
  GOOGLE_SHEETS: "Google Sheets",
  ALL_FINANCE: "All Finance",
  CHECKLIST_V1: "Checklist (v1)",
  AUTOMATION: "Facebook Automation",
  TECH_SUPPORT: "Tech Support",
  MAINTENANCE: "Maintenance",
  INCENTIVES: "Incentives",
  OTHER_PRODUCTS: "Other Products",
  RULE_CONFIGURATIONS: "Rule Configurations",
  CLIENT_PORTAL: "Client Portal",
  CLIENT_DOCUMENTS: "Client Documents",
  V2_PLACEHOLDER: "API v2 (Future)",
} as const;

export const tags: OpenAPIV3.TagObject[] = [
  { name: TAG_NAMES.SYSTEM, description: "Health checks and system endpoints" },
  { name: TAG_NAMES.AUTH, description: "Login, refresh, logout, and session management" },
  { name: TAG_NAMES.USERS, description: "User management and directory endpoints" },
  { name: TAG_NAMES.ROLES, description: "RBAC roles, permissions, and user-role assignments" },
  { name: TAG_NAMES.TEAMS, description: "Team CRUD operations" },
  { name: TAG_NAMES.SALE_TYPES, description: "Sale type master data" },
  { name: TAG_NAMES.SALE_TYPE_CATEGORIES, description: "Sale type category master data" },
  { name: TAG_NAMES.LEAD_TYPES, description: "Lead type master data" },
  { name: TAG_NAMES.LEADS, description: "Lead lifecycle, assignment, and reporting" },
  { name: TAG_NAMES.LEAD_REGISTRATION, description: "Inbound lead registration webhooks" },
  { name: TAG_NAMES.FRONT_DESK, description: "Front desk lead verification and assignment" },
  { name: TAG_NAMES.CLIENTS, description: "Client records, archive, and transfer" },
  { name: TAG_NAMES.CLIENT_PAYMENTS, description: "Legacy client payment records" },
  { name: TAG_NAMES.CLIENT_PRODUCT_PAYMENTS, description: "Client product payment records" },
  { name: TAG_NAMES.MODULE_PAYMENTS, description: "Modular payment database APIs (DATABASE_URL_SECOND)" },
  { name: TAG_NAMES.MODULE_COUNTRIES, description: "Countries master data (modules database)" },
  { name: TAG_NAMES.MODULE_JOURNEY, description: "Client journey timeline and stage tracking (modules database)" },
  { name: TAG_NAMES.MODULE_REPORTS, description: "Backend, binding, CX, and ops analytics reports (modules database)" },
  { name: TAG_NAMES.MODULE_VISA_CASES, description: "Visa case lifecycle, assignments, and documents (modules database)" },
  { name: TAG_NAMES.MODULE_STAGES, description: "Admin-managed stage pipelines for client journey, visa case processing, and payments (modules database)" },
  { name: TAG_NAMES.DASHBOARD, description: "Role-based dashboard statistics" },
  { name: TAG_NAMES.ACTIVITY_LOGS, description: "User activity audit logs" },
  { name: TAG_NAMES.LEADERBOARD, description: "Counsellor leaderboard and targets" },
  { name: TAG_NAMES.MANAGER_TARGETS, description: "Manager revenue targets" },
  { name: TAG_NAMES.TELECALLER_TARGETS, description: "Telecaller monthly targets" },
  { name: TAG_NAMES.REPORTS, description: "Sales and counsellor reports" },
  { name: TAG_NAMES.MESSAGES, description: "Broadcast messages and inbox" },
  { name: TAG_NAMES.GOOGLE_SHEETS, description: "Google Sheets integration" },
  { name: TAG_NAMES.ALL_FINANCE, description: "All-finance payment approvals" },
  { name: TAG_NAMES.CHECKLIST_V1, description: "Public checklist API (versioned under /api/v1)" },
  { name: TAG_NAMES.AUTOMATION, description: "Facebook lead automation and Meta conversions" },
  { name: TAG_NAMES.TECH_SUPPORT, description: "Support tickets, devices, and inventory" },
  { name: TAG_NAMES.MAINTENANCE, description: "Maintenance mode toggle" },
  { name: TAG_NAMES.INCENTIVES, description: "Incentive rules and payout reports" },
  { name: TAG_NAMES.OTHER_PRODUCTS, description: "Other products catalog" },
  { name: TAG_NAMES.RULE_CONFIGURATIONS, description: "Incentive rule configuration groups" },
  { name: TAG_NAMES.CLIENT_PORTAL, description: "Client portal invitation and client auth/session APIs" },
  { name: TAG_NAMES.CLIENT_DOCUMENTS, description: "Client checklist assignment, document upload, and storage (modules DB)" },
  { name: TAG_NAMES.V2_PLACEHOLDER, description: "Reserved for future v2 API endpoints" },
];
