import { TAG_NAMES } from "../../tags/tags";
import { buildPaths, jsonBody, param } from "../../utils/routeBuilder";

const automationRoles = ["superadmin", "admin", "developer", "manager"];

export const automationPaths = buildPaths([
  { method: "get", path: "/api/automation/facebook/callback", tag: TAG_NAMES.AUTOMATION, summary: "Facebook OAuth callback", secured: false },
  { method: "get", path: "/api/automation/facebook/webhook", tag: TAG_NAMES.AUTOMATION, summary: "Verify Facebook webhook", secured: false },
  { method: "post", path: "/api/automation/facebook/webhook", tag: TAG_NAMES.AUTOMATION, summary: "Facebook webhook handler", secured: false, description: "Uses raw JSON body for signature verification." },
  { method: "get", path: "/api/automation/facebook/auth-url", tag: TAG_NAMES.AUTOMATION, summary: "Get Facebook auth URL", roles: automationRoles },
  { method: "get", path: "/api/automation/facebook/status", tag: TAG_NAMES.AUTOMATION, summary: "Facebook connection status", roles: automationRoles },
  { method: "post", path: "/api/automation/facebook/disconnect", tag: TAG_NAMES.AUTOMATION, summary: "Disconnect Facebook", roles: automationRoles },
  { method: "get", path: "/api/automation/facebook/pages", tag: TAG_NAMES.AUTOMATION, summary: "List Facebook pages", roles: automationRoles },
  { method: "get", path: "/api/automation/facebook/active-forms", tag: TAG_NAMES.AUTOMATION, summary: "List active Facebook forms", roles: automationRoles },
  { method: "get", path: "/api/automation/facebook/manual-distribution/leads", tag: TAG_NAMES.AUTOMATION, summary: "Manual distribution leads", roles: automationRoles },
  { method: "get", path: "/api/automation/facebook/manual-distribution/by-assignee", tag: TAG_NAMES.AUTOMATION, summary: "Manual distribution by assignee stats", roles: automationRoles },
  {
    method: "post",
    path: "/api/automation/facebook/manual-distribution/distribute-bulk",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Bulk manual lead distribution",
    roles: automationRoles,
    requestBody: jsonBody("SuccessResponse", "Bulk distribution payload"),
  },
  { method: "get", path: "/api/automation/facebook/leads", tag: TAG_NAMES.AUTOMATION, summary: "Imported Facebook leads", roles: automationRoles },
  { method: "get", path: "/api/automation/facebook/events", tag: TAG_NAMES.AUTOMATION, summary: "Facebook events (SSE)", roles: automationRoles, description: "Server-Sent Events stream." },
  { method: "get", path: "/api/automation/meta-conversions/status", tag: TAG_NAMES.AUTOMATION, summary: "Meta conversions status", roles: automationRoles },
  {
    method: "post",
    path: "/api/automation/meta-conversions/send",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Send Meta conversion events",
    roles: automationRoles,
    requestBody: jsonBody("SuccessResponse", "Conversion events payload"),
  },
  {
    method: "get",
    path: "/api/automation/facebook/forms/{pageId}",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Facebook forms for page",
    roles: automationRoles,
    parameters: [param.path("pageId", "Facebook page ID")],
  },
  {
    method: "post",
    path: "/api/automation/facebook/forms/{pageId}/{formId}/toggle",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Toggle Facebook form",
    roles: automationRoles,
    parameters: [
      param.path("pageId", "Facebook page ID"),
      param.path("formId", "Facebook form ID"),
    ],
  },
  {
    method: "get",
    path: "/api/automation/facebook/forms/{formId}/strategy",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Get form distribution strategy",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
  },
  {
    method: "put",
    path: "/api/automation/facebook/forms/{formId}/strategy",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Set form distribution strategy",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
    requestBody: jsonBody("SuccessResponse", "Strategy configuration"),
  },
  {
    method: "get",
    path: "/api/automation/facebook/forms/{formId}/stats",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Form stats",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
  },
  {
    method: "get",
    path: "/api/automation/facebook/forms/{formId}/paginated-leads",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Paginated form leads",
    roles: automationRoles,
    parameters: [
      param.path("formId", "Facebook form ID"),
      param.query("page", "Page number", false, "integer"),
      param.query("limit", "Page size", false, "integer"),
    ],
    successResponse: "PaginatedResponse",
  },
  {
    method: "get",
    path: "/api/automation/facebook/forms/{formId}/export",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Export form leads CSV",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
  },
  {
    method: "post",
    path: "/api/automation/facebook/forms/{formId}/distribute-manual",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Manual lead distribution for form",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
    requestBody: jsonBody("SuccessResponse", "Manual distribution payload"),
  },
  {
    method: "get",
    path: "/api/automation/facebook/forms/{formId}/preview",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Preview Facebook lead",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
  },
  {
    method: "post",
    path: "/api/automation/facebook/forms/{formId}/import",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Import form leads",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
  },
  {
    method: "post",
    path: "/api/automation/facebook/forms/stats-bulk",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Bulk form stats",
    roles: automationRoles,
    requestBody: jsonBody("SuccessResponse", "Form ID list"),
    requestExample: { formIds: ["123456", "789012"] },
  },
  { method: "get", path: "/api/automation/facebook/master-distribution", tag: TAG_NAMES.AUTOMATION, summary: "Get master distribution config", roles: automationRoles },
  {
    method: "post",
    path: "/api/automation/facebook/master-distribution",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Save master distribution config",
    roles: automationRoles,
    requestBody: jsonBody("SuccessResponse", "Master distribution config"),
  },
  {
    method: "delete",
    path: "/api/automation/facebook/master-distribution/{formId}",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Deactivate master form",
    roles: automationRoles,
    parameters: [param.path("formId", "Facebook form ID")],
  },
  {
    method: "get",
    path: "/api/automation/facebook/manual-distribution/forms-with-unassigned-leads",
    tag: TAG_NAMES.AUTOMATION,
    summary: "Forms with unassigned leads",
    roles: automationRoles,
  },
]);
