import { TAG_NAMES } from "../../tags/tags";
import { buildPaths, jsonBody, param } from "../../utils/routeBuilder";

const checklistAdminRoles = ["admin", "superadmin", "developer"];

export const checklistPaths = buildPaths([
  { method: "get", path: "/api/v1/categories", tag: TAG_NAMES.CHECKLIST_V1, summary: "List checklist categories", secured: false },
  {
    method: "get",
    path: "/api/v1/categories/{slug}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Category by slug",
    secured: false,
    parameters: [param.path("slug", "Category slug")],
  },
  { method: "get", path: "/api/v1/countries", tag: TAG_NAMES.CHECKLIST_V1, summary: "List countries", secured: false },
  { method: "get", path: "/api/v1/checklists", tag: TAG_NAMES.CHECKLIST_V1, summary: "List checklists", secured: false },
  {
    method: "get",
    path: "/api/v1/checklists/{slug}/sections",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Checklist sections by slug",
    secured: false,
    parameters: [param.path("slug", "Checklist slug")],
  },
  {
    method: "get",
    path: "/api/v1/checklists/{slug}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Checklist by slug",
    secured: false,
    parameters: [param.path("slug", "Checklist slug")],
  },
  {
    method: "get",
    path: "/api/v1/search",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Search checklists",
    secured: false,
    parameters: [param.query("q", "Search query", true)],
  },
  {
    method: "post",
    path: "/api/v1/admin/countries",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Create country",
    roles: checklistAdminRoles,
    requestBody: jsonBody("SuccessResponse", "Country payload"),
    requestExample: { name: "Canada", code: "CA" },
  },
  {
    method: "post",
    path: "/api/v1/admin/checklists",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Create checklist",
    roles: checklistAdminRoles,
    requestBody: jsonBody("SuccessResponse", "Checklist payload"),
  },
  {
    method: "post",
    path: "/api/v1/admin/checklists/{checklistId}/sections",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Create checklist section",
    roles: checklistAdminRoles,
    parameters: [param.path("checklistId", "Checklist ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Section payload"),
  },
  {
    method: "post",
    path: "/api/v1/admin/sections/{sectionId}/items",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Create checklist item",
    roles: checklistAdminRoles,
    parameters: [param.path("sectionId", "Section ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Item payload"),
  },
  {
    method: "put",
    path: "/api/v1/admin/checklists/{id}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Update checklist",
    roles: checklistAdminRoles,
    parameters: [param.path("id", "Checklist ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Checklist update"),
  },
  {
    method: "put",
    path: "/api/v1/admin/sections/{id}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Update section",
    roles: checklistAdminRoles,
    parameters: [param.path("id", "Section ID", "integer")],
  },
  {
    method: "put",
    path: "/api/v1/admin/items/{id}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Update item",
    roles: checklistAdminRoles,
    parameters: [param.path("id", "Item ID", "integer")],
  },
  {
    method: "delete",
    path: "/api/v1/admin/checklists/{id}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Delete checklist",
    roles: checklistAdminRoles,
    parameters: [param.path("id", "Checklist ID", "integer")],
  },
  {
    method: "delete",
    path: "/api/v1/admin/sections/{id}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Delete section",
    roles: checklistAdminRoles,
    parameters: [param.path("id", "Section ID", "integer")],
  },
  {
    method: "delete",
    path: "/api/v1/admin/items/{id}",
    tag: TAG_NAMES.CHECKLIST_V1,
    summary: "Delete item",
    roles: checklistAdminRoles,
    parameters: [param.path("id", "Item ID", "integer")],
  },
]);
