import { TAG_NAMES } from "../../tags/tags";
import { buildPaths, jsonBody, param } from "../../utils/routeBuilder";

const leadWriteRoles = ["developer", "admin", "manager", "telecaller", "counsellor"];

export const leadsPaths = buildPaths([
  { method: "get", path: "/api/leads", tag: TAG_NAMES.LEADS, summary: "List leads", successResponse: "PaginatedResponse" },
  {
    method: "get",
    path: "/api/leads/reference/clients",
    tag: TAG_NAMES.LEADS,
    summary: "Search reference clients",
    roles: ["telecaller", "counsellor", "manager", "admin", "developer", "superadmin", "marketing_head"],
    parameters: [param.query("q", "Search query")],
  },
  { method: "get", path: "/api/leads/reports", tag: TAG_NAMES.LEADS, summary: "Lead reports" },
  { method: "get", path: "/api/leads/leaderboard/telecallers", tag: TAG_NAMES.LEADS, summary: "Telecaller leaderboard" },
  { method: "get", path: "/api/leads/telecaller-summary", tag: TAG_NAMES.LEADS, summary: "Telecaller lead summary" },
  {
    method: "get",
    path: "/api/leads/telecaller/{id}/report",
    tag: TAG_NAMES.LEADS,
    summary: "Telecaller individual report",
    parameters: [param.path("id", "Telecaller user ID", "integer")],
  },
  {
    method: "get",
    path: "/api/leads/counsellor-report",
    tag: TAG_NAMES.LEADS,
    summary: "Counsellor individual report",
    roles: ["counsellor", "manager", "admin", "developer", "superadmin"],
  },
  { method: "get", path: "/api/leads/telecaller-dashboard-stats", tag: TAG_NAMES.LEADS, summary: "Telecaller dashboard stats" },
  {
    method: "get",
    path: "/api/leads/import/template",
    tag: TAG_NAMES.LEADS,
    summary: "Download lead import CSV template",
    roles: ["developer", "admin", "manager", "superadmin"],
  },
  {
    method: "post",
    path: "/api/leads/import",
    tag: TAG_NAMES.LEADS,
    summary: "Import leads from CSV",
    roles: ["developer", "admin", "manager", "superadmin"],
    description: "Multipart form upload with CSV file.",
  },
  {
    method: "post",
    path: "/api/leads/bulk-assign",
    tag: TAG_NAMES.LEADS,
    summary: "Bulk assign leads",
    roles: ["developer", "admin", "manager", "superadmin"],
    requestBody: jsonBody("SuccessResponse", "Bulk assign payload"),
    requestExample: { leadIds: [1, 2, 3], assigneeId: 42, role: "telecaller" },
  },
  {
    method: "get",
    path: "/api/leads/{id}",
    tag: TAG_NAMES.LEADS,
    summary: "Get lead by ID",
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/leads",
    tag: TAG_NAMES.LEADS,
    summary: "Create lead",
    roles: leadWriteRoles,
    requestBody: jsonBody("SuccessResponse", "Lead payload"),
  },
  {
    method: "put",
    path: "/api/leads/{id}",
    tag: TAG_NAMES.LEADS,
    summary: "Update lead",
    roles: leadWriteRoles,
    parameters: [param.path("id", "Lead ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Lead fields to update"),
  },
  {
    method: "post",
    path: "/api/leads/{id}/activities",
    tag: TAG_NAMES.LEADS,
    summary: "Add lead activity",
    roles: leadWriteRoles,
    parameters: [param.path("id", "Lead ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Activity payload"),
  },
  {
    method: "post",
    path: "/api/leads/{id}/assign",
    tag: TAG_NAMES.LEADS,
    summary: "Assign lead",
    roles: leadWriteRoles,
    parameters: [param.path("id", "Lead ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Assignment payload"),
  },
  {
    method: "post",
    path: "/api/leads/{id}/junk",
    tag: TAG_NAMES.LEADS,
    summary: "Mark lead as junk",
    roles: ["developer", "admin", "manager", "superadmin", "telecaller"],
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/leads/{id}/revert-junk",
    tag: TAG_NAMES.LEADS,
    summary: "Revert junk lead",
    roles: ["developer", "admin", "manager", "superadmin"],
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/leads/{id}/convert-to-client",
    tag: TAG_NAMES.LEADS,
    summary: "Convert lead to client",
    roles: ["counsellor"],
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/leads/{id}/drop",
    tag: TAG_NAMES.LEADS,
    summary: "Drop lead",
    roles: ["counsellor"],
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/leads/{id}/followup",
    tag: TAG_NAMES.LEADS,
    summary: "Mark lead follow-up",
    roles: leadWriteRoles,
    parameters: [param.path("id", "Lead ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Follow-up payload"),
  },
  {
    method: "put",
    path: "/api/leads/{id}/activities/{activityId}/status",
    tag: TAG_NAMES.LEADS,
    summary: "Update lead activity status",
    roles: leadWriteRoles,
    parameters: [
      param.path("id", "Lead ID", "integer"),
      param.path("activityId", "Activity ID", "integer"),
    ],
    requestBody: jsonBody("SuccessResponse", "Status update"),
  },
]);

export const leadRegistrationPaths = buildPaths([
  {
    method: "post",
    path: "/api/lead-registration/inbound",
    tag: TAG_NAMES.LEAD_REGISTRATION,
    summary: "Inbound lead registration webhook",
    secured: false,
    description: "Server-to-server endpoint verified via HMAC signature headers (X-Timestamp, X-Signature).",
    requestBody: jsonBody("SuccessResponse", "Lead registration payload"),
  },
]);

export const frontDeskPaths = buildPaths([
  { method: "get", path: "/api/front-desk/stats", tag: TAG_NAMES.FRONT_DESK, summary: "Front desk dashboard stats", roles: ["front_desk", "developer"] },
  { method: "get", path: "/api/front-desk/leads", tag: TAG_NAMES.FRONT_DESK, summary: "List front desk leads", roles: ["front_desk", "developer"] },
  { method: "get", path: "/api/front-desk/leads/export", tag: TAG_NAMES.FRONT_DESK, summary: "Export front desk leads", roles: ["front_desk", "developer"] },
  {
    method: "get",
    path: "/api/front-desk/leads/{id}",
    tag: TAG_NAMES.FRONT_DESK,
    summary: "Front desk lead detail",
    roles: ["front_desk", "developer"],
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/front-desk/leads/{id}/verify",
    tag: TAG_NAMES.FRONT_DESK,
    summary: "Verify lead",
    roles: ["front_desk", "developer"],
    parameters: [param.path("id", "Lead ID", "integer")],
  },
  {
    method: "post",
    path: "/api/front-desk/leads/{id}/assign",
    tag: TAG_NAMES.FRONT_DESK,
    summary: "Assign lead",
    roles: ["front_desk", "developer"],
    parameters: [param.path("id", "Lead ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Assignment payload"),
  },
  {
    method: "put",
    path: "/api/front-desk/leads/{id}",
    tag: TAG_NAMES.FRONT_DESK,
    summary: "Update lead details",
    roles: ["front_desk", "developer"],
    parameters: [param.path("id", "Lead ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Lead update payload"),
  },
  { method: "get", path: "/api/front-desk/counsellors", tag: TAG_NAMES.FRONT_DESK, summary: "Counsellors for assignment", roles: ["front_desk", "developer"] },
  { method: "get", path: "/api/front-desk/sale-types", tag: TAG_NAMES.FRONT_DESK, summary: "Sale types for front desk", roles: ["front_desk", "developer"] },
  { method: "get", path: "/api/front-desk/activity", tag: TAG_NAMES.FRONT_DESK, summary: "Activity logs", roles: ["front_desk", "developer", "admin", "superadmin"] },
]);
