import { TAG_NAMES } from "../../tags/tags";
import { buildPaths, jsonBody, param } from "../../utils/routeBuilder";

const adminRoles = ["admin", "superadmin"];

export const rolesPaths = buildPaths([
  {
    method: "get",
    path: "/api/role/roles",
    tag: TAG_NAMES.ROLES,
    summary: "List roles",
    roles: adminRoles,
    successResponse: "PaginatedResponse",
  },
  {
    method: "get",
    path: "/api/role/roles/{roleId}",
    tag: TAG_NAMES.ROLES,
    summary: "Get role by ID",
    roles: adminRoles,
    parameters: [param.path("roleId", "Role ID", "integer")],
    responseExample: { id: 3, name: "counsellor", description: "Counsellor role" },
  },
  {
    method: "post",
    path: "/api/role/roles",
    tag: TAG_NAMES.ROLES,
    summary: "Create role",
    roles: adminRoles,
    requestBody: jsonBody("CreateRoleRequest", "New role"),
    requestExample: { name: "marketing_head", description: "Marketing head" },
  },
  {
    method: "put",
    path: "/api/role/roles/{roleId}",
    tag: TAG_NAMES.ROLES,
    summary: "Update role",
    roles: adminRoles,
    parameters: [param.path("roleId", "Role ID", "integer")],
    requestBody: jsonBody("UpdateRoleRequest", "Role fields to update"),
  },
  {
    method: "delete",
    path: "/api/role/roles/{roleId}",
    tag: TAG_NAMES.ROLES,
    summary: "Delete role",
    roles: adminRoles,
    parameters: [param.path("roleId", "Role ID", "integer")],
  },
  {
    method: "get",
    path: "/api/role/permissions",
    tag: TAG_NAMES.ROLES,
    summary: "List permissions",
    roles: adminRoles,
  },
  {
    method: "get",
    path: "/api/role/permissions/{permissionId}",
    tag: TAG_NAMES.ROLES,
    summary: "Get permission by ID",
    roles: adminRoles,
    parameters: [param.path("permissionId", "Permission ID", "integer")],
  },
  {
    method: "post",
    path: "/api/role/permissions",
    tag: TAG_NAMES.ROLES,
    summary: "Create permission",
    roles: adminRoles,
    requestBody: jsonBody("CreateRoleRequest", "Permission name and description"),
  },
  {
    method: "put",
    path: "/api/role/permissions/{permissionId}",
    tag: TAG_NAMES.ROLES,
    summary: "Update permission",
    roles: adminRoles,
    parameters: [param.path("permissionId", "Permission ID", "integer")],
  },
  {
    method: "delete",
    path: "/api/role/permissions/{permissionId}",
    tag: TAG_NAMES.ROLES,
    summary: "Delete permission",
    roles: adminRoles,
    parameters: [param.path("permissionId", "Permission ID", "integer")],
  },
  {
    method: "get",
    path: "/api/role/roles/{roleId}/permissions",
    tag: TAG_NAMES.ROLES,
    summary: "List permissions for a role",
    roles: adminRoles,
    parameters: [param.path("roleId", "Role ID", "integer")],
  },
  {
    method: "put",
    path: "/api/role/roles/{roleId}/permissions",
    tag: TAG_NAMES.ROLES,
    summary: "Replace role permissions",
    roles: adminRoles,
    parameters: [param.path("roleId", "Role ID", "integer")],
    requestBody: jsonBody("RolePermissionsUpdateRequest", "Permission ID list"),
    requestExample: { permissionIds: [1, 2, 5] },
  },
  {
    method: "post",
    path: "/api/role/roles/{roleId}/permissions/{permissionId}",
    tag: TAG_NAMES.ROLES,
    summary: "Add permission to role",
    roles: adminRoles,
    parameters: [
      param.path("roleId", "Role ID", "integer"),
      param.path("permissionId", "Permission ID", "integer"),
    ],
  },
  {
    method: "delete",
    path: "/api/role/roles/{roleId}/permissions/{permissionId}",
    tag: TAG_NAMES.ROLES,
    summary: "Remove permission from role",
    roles: adminRoles,
    parameters: [
      param.path("roleId", "Role ID", "integer"),
      param.path("permissionId", "Permission ID", "integer"),
    ],
  },
  {
    method: "get",
    path: "/api/role/users/{userId}/roles",
    tag: TAG_NAMES.ROLES,
    summary: "List roles assigned to user",
    roles: adminRoles,
    parameters: [param.path("userId", "User ID", "integer")],
  },
  {
    method: "put",
    path: "/api/role/users/{userId}/primary-role",
    tag: TAG_NAMES.ROLES,
    summary: "Set user primary role",
    roles: adminRoles,
    parameters: [param.path("userId", "User ID", "integer")],
    requestBody: jsonBody("SetUserPrimaryRoleRequest", "Primary role ID"),
    requestExample: { roleId: 3 },
  },
]);
