import { TAG_NAMES } from "../../tags/tags";
import { buildPaths, jsonBody, param } from "../../utils/routeBuilder";

const techRoles = ["tech_support", "admin", "superadmin", "manager"];

export const techSupportPaths = buildPaths([
  {
    method: "post",
    path: "/api/tech-support/tickets",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Create support ticket",
    requestBody: jsonBody("SuccessResponse", "Ticket payload"),
    requestExample: { title: "Laptop not booting", description: "Device fails to start after update", priority: "high" },
  },
  { method: "get", path: "/api/tech-support/tickets/my", tag: TAG_NAMES.TECH_SUPPORT, summary: "My support tickets" },
  {
    method: "post",
    path: "/api/tech-support/requests",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Create support request",
    requestBody: jsonBody("SuccessResponse", "Support request payload"),
  },
  { method: "get", path: "/api/tech-support/requests/my", tag: TAG_NAMES.TECH_SUPPORT, summary: "My support requests" },
  { method: "get", path: "/api/tech-support/requests", tag: TAG_NAMES.TECH_SUPPORT, summary: "All support requests", roles: techRoles },
  {
    method: "patch",
    path: "/api/tech-support/requests/{id}/review",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Review support request",
    parameters: [param.path("id", "Request ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Review decision"),
  },
  { method: "get", path: "/api/tech-support/board", tag: TAG_NAMES.TECH_SUPPORT, summary: "Support board", roles: techRoles },
  {
    method: "get",
    path: "/api/tech-support/tickets/{id}",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Ticket details",
    roles: ["counsellor", ...techRoles],
    parameters: [param.path("id", "Ticket ID", "integer")],
  },
  {
    method: "post",
    path: "/api/tech-support/tickets/{id}/claim",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Claim ticket",
    roles: techRoles,
    parameters: [param.path("id", "Ticket ID", "integer")],
  },
  {
    method: "patch",
    path: "/api/tech-support/tickets/{id}/status",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Update ticket status",
    roles: techRoles,
    parameters: [param.path("id", "Ticket ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Status update"),
    requestExample: { status: "in_progress" },
  },
  {
    method: "post",
    path: "/api/tech-support/approve/{id}",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Approve ticket resolution",
    parameters: [param.path("id", "Ticket ID", "integer")],
  },
  { method: "get", path: "/api/tech-support/analytics/overview", tag: TAG_NAMES.TECH_SUPPORT, summary: "Support analytics overview", roles: ["admin", "superadmin", "manager"] },
  {
    method: "post",
    path: "/api/tech-support/tickets/{ticketId}/images",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Upload ticket images (max 2)",
    roles: ["counsellor", ...techRoles],
    parameters: [param.path("ticketId", "Ticket ID", "integer")],
    description: "Multipart form upload with image files.",
  },
  {
    method: "delete",
    path: "/api/tech-support/tickets/{ticketId}/images/{filename}",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Delete ticket image",
    roles: ["counsellor", ...techRoles],
    parameters: [
      param.path("ticketId", "Ticket ID", "integer"),
      param.path("filename", "Image filename"),
    ],
  },
  { method: "get", path: "/api/tech-support/devices", tag: TAG_NAMES.TECH_SUPPORT, summary: "List device inventory", roles: techRoles },
  { method: "get", path: "/api/tech-support/devices/available", tag: TAG_NAMES.TECH_SUPPORT, summary: "Available devices", roles: techRoles },
  {
    method: "get",
    path: "/api/tech-support/devices/assigned-to/{userId}",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Device assigned to user",
    roles: techRoles,
    parameters: [param.path("userId", "User ID", "integer")],
  },
  {
    method: "post",
    path: "/api/tech-support/devices",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Create device",
    roles: techRoles,
    requestBody: jsonBody("SuccessResponse", "Device payload"),
    requestExample: { serialNumber: "SN-12345", type: "laptop", model: "Dell Latitude 5540" },
  },
  {
    method: "post",
    path: "/api/tech-support/devices/bulk",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Bulk create devices",
    roles: techRoles,
    requestBody: jsonBody("SuccessResponse", "Device list"),
  },
  { method: "get", path: "/api/tech-support/devices/assignable-users", tag: TAG_NAMES.TECH_SUPPORT, summary: "Users assignable to devices", roles: techRoles },
  {
    method: "patch",
    path: "/api/tech-support/users/{userId}/retained-accessories",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Update user retained accessories",
    roles: techRoles,
    parameters: [param.path("userId", "User ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Retained accessories"),
    requestExample: { retainedAccessories: "charger,mouse" },
  },
  {
    method: "post",
    path: "/api/tech-support/devices/{deviceId}/assign",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Assign device",
    roles: techRoles,
    parameters: [param.path("deviceId", "Device ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Assignment payload"),
    requestExample: { userId: 42 },
  },
  {
    method: "post",
    path: "/api/tech-support/devices/{deviceId}/unassign",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Unassign device",
    roles: techRoles,
    parameters: [param.path("deviceId", "Device ID", "integer")],
  },
  { method: "get", path: "/api/tech-support/devices/assignment-history", tag: TAG_NAMES.TECH_SUPPORT, summary: "Device assignment history", roles: techRoles },
  {
    method: "patch",
    path: "/api/tech-support/devices/{deviceId}/repair",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Toggle device repair status",
    roles: techRoles,
    parameters: [param.path("deviceId", "Device ID", "integer")],
  },
  {
    method: "delete",
    path: "/api/tech-support/devices/{deviceId}",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Delete device",
    roles: techRoles,
    parameters: [param.path("deviceId", "Device ID", "integer")],
  },
  {
    method: "patch",
    path: "/api/tech-support/devices/{deviceId}",
    tag: TAG_NAMES.TECH_SUPPORT,
    summary: "Update device",
    roles: techRoles,
    parameters: [param.path("deviceId", "Device ID", "integer")],
    requestBody: jsonBody("SuccessResponse", "Device fields to update"),
  },
]);
