import { TAG_NAMES } from "../../tags/tags";
import { buildPaths, jsonBody, param } from "../../utils/routeBuilder";

export const usersPaths = buildPaths([
  {
    method: "post",
    path: "/api/users/login",
    tag: TAG_NAMES.AUTH,
    summary: "Login",
    secured: false,
    description: "Authenticate with email/password. Returns JWT access token and CSRF token.",
    requestBody: jsonBody("LoginRequest", "Login credentials"),
    successResponse: "AuthenticationResponse",
    requestExample: { email: "jane.doe@example.com", password: "SecurePass123!" },
  },
  {
    method: "post",
    path: "/api/users/refresh",
    tag: TAG_NAMES.AUTH,
    summary: "Refresh access token",
    secured: false,
    requestBody: jsonBody("RefreshTokenRequest", "Refresh token (optional if sent via cookie/header)", false),
    successResponse: "AuthenticationResponse",
  },
  {
    method: "post",
    path: "/api/users/logout",
    tag: TAG_NAMES.AUTH,
    summary: "Logout",
    description: "Revokes the current session and clears auth cookies.",
  },
  {
    method: "get",
    path: "/api/users/me",
    tag: TAG_NAMES.AUTH,
    summary: "Get current user profile",
    responseExample: {
      id: 42,
      fullName: "Jane Doe",
      email: "jane.doe@example.com",
      role: "counsellor",
    },
  },
  {
    method: "put",
    path: "/api/users/change-password",
    tag: TAG_NAMES.AUTH,
    summary: "Change password",
    requestBody: jsonBody("ChangePasswordRequest", "Current and new password"),
    requestExample: { currentPassword: "OldPass123!", newPassword: "NewPass456!" },
  },
  {
    method: "post",
    path: "/api/users/register",
    tag: TAG_NAMES.USERS,
    summary: "Register user",
    roles: ["developer", "admin"],
    requestBody: jsonBody("RegisterUserRequest", "New user payload"),
    requestExample: {
      fullName: "Jane Doe",
      email: "jane.doe@example.com",
      password: "SecurePass123!",
      role: "counsellor",
      teamId: 2,
      managerId: 7,
    },
  },
  {
    method: "get",
    path: "/api/users/users",
    tag: TAG_NAMES.USERS,
    summary: "List all users",
    roles: ["developer", "admin"],
    successResponse: "PaginatedResponse",
  },
  {
    method: "get",
    path: "/api/users/users/details",
    tag: TAG_NAMES.USERS,
    summary: "List all users with extended details",
    roles: ["developer", "admin", "manager"],
  },
  {
    method: "put",
    path: "/api/users/users-update/{userId}",
    tag: TAG_NAMES.USERS,
    summary: "Update user",
    roles: ["developer", "admin"],
    parameters: [param.path("userId", "User ID", "integer")],
    requestBody: jsonBody("UpdateUserRequest", "Fields to update"),
  },
  {
    method: "delete",
    path: "/api/users/users-delete/{userId}",
    tag: TAG_NAMES.USERS,
    summary: "Delete user",
    roles: ["developer", "admin"],
    parameters: [param.path("userId", "User ID", "integer")],
  },
  {
    method: "get",
    path: "/api/users/managers",
    tag: TAG_NAMES.USERS,
    summary: "Managers dropdown",
    roles: ["developer", "admin"],
  },
  {
    method: "get",
    path: "/api/users/counsellors",
    tag: TAG_NAMES.USERS,
    summary: "Counsellors list",
    roles: ["developer", "admin", "counsellor", "telecaller", "marketing_head"],
  },
  {
    method: "get",
    path: "/api/users/managers/{managerId}/counsellors",
    tag: TAG_NAMES.USERS,
    summary: "Counsellors by manager",
    roles: ["developer", "admin"],
    parameters: [param.path("managerId", "Manager user ID", "integer")],
  },
  {
    method: "get",
    path: "/api/users/managers-with-counsellors",
    tag: TAG_NAMES.USERS,
    summary: "Managers with nested counsellors",
    roles: ["developer", "admin"],
  },
  {
    method: "get",
    path: "/api/users/telecallers",
    tag: TAG_NAMES.USERS,
    summary: "Telecallers dropdown",
    roles: ["developer", "admin", "manager", "telecaller", "counsellor", "marketing_head"],
  },
  {
    method: "get",
    path: "/api/users/health",
    tag: TAG_NAMES.SYSTEM,
    summary: "Users module health check",
    secured: false,
  },
]);
